export const participants = [
    {
        audioOutputDeviceId: 'default',
        avatarURL: undefined,
        botType: undefined,
        conference: undefined,
        connectionStatus: undefined,
        dominantSpeaker: false,
        email: undefined,
        id: 'd0816677',
        isFakeParticipant: undefined,
        isJigasi: undefined,
        loadableAvatarUrl: undefined,
        local: true,
        name: 'testuser2',
        pinned: false,
        presence: undefined,
        role: 'moderator',
        startWithAudioMuted: true,
        startWithVideoMuted: true
    },
    {
        audioOutputDeviceId: 'default',
        avatarURL: undefined,
        botType: undefined,
        conference: undefined,
        connectionStatus: undefined,
        dominantSpeaker: false,
        email: undefined,
        id: 'a0496597',
        isFakeParticipant: undefined,
        isJigasi: undefined,
        loadableAvatarUrl: undefined,
        local: true,
        name: 'me',
        pinned: false,
        presence: undefined,
        role: 'participant',
        startWithAudioMuted: true,
        startWithVideoMuted: false
    },
    {
        audioOutputDeviceId: 'default',
        avatarURL: undefined,
        botType: undefined,
        conference: undefined,
        connectionStatus: undefined,
        dominantSpeaker: false,
        email: undefined,
        id: 'b01081018',
        isFakeParticipant: undefined,
        isJigasi: undefined,
        loadableAvatarUrl: undefined,
        local: true,
        name: 'Tom',
        pinned: false,
        presence: undefined,
        role: 'participant',
        startWithAudioMuted: true,
        startWithVideoMuted: false
    },
    {
        audioOutputDeviceId: 'default',
        avatarURL: undefined,
        botType: undefined,
        conference: undefined,
        connectionStatus: undefined,
        dominantSpeaker: false,
        email: undefined,
        id: 'b0aad221e1',
        isFakeParticipant: undefined,
        isJigasi: undefined,
        loadableAvatarUrl: undefined,
        local: true,
        name: 'George',
        pinned: false,
        presence: undefined,
        role: 'participant',
        startWithAudioMuted: true,
        startWithVideoMuted: false
    },
    {
        audioOutputDeviceId: 'default',
        avatarURL: undefined,
        botType: undefined,
        conference: undefined,
        connectionStatus: undefined,
        dominantSpeaker: false,
        email: undefined,
        id: 'c0108301',
        isFakeParticipant: undefined,
        isJigasi: undefined,
        loadableAvatarUrl: undefined,
        local: true,
        name: 'Carlin',
        pinned: false,
        presence: undefined,
        role: 'participant',
        startWithAudioMuted: true,
        startWithVideoMuted: false
    }
];
