var interfaceConfig = {
    CANVAS_EXTRA: 104,
    CANVAS_RADIUS: 7,
    SHADOW_COLOR: '#00ccff',
    INITIAL_TOOLBAR_TIMEOUT: 20000,
    TOOLBAR_TIMEOUT: 4000,
    DEFAULT_REMOTE_DISPLAY_NAME: "Fellow Jitster",
    DEFAULT_DOMINANT_SPEAKER_DISPLAY_NAME: "Speaker"
};
