#!/usr/bin/with-contenv bash

if [[ $DISABLE_HTTPS -ne 1 ]] && \
   [[ $ENABLE_LETSENCRYPT -eq 1 ]]; then
    exec cron -f
else
    # if cron should not be started,
    # prevent s6 from restarting this script again and again
    s6-svc -O /var/run/s6/services/cron
fi
