export const smileys = {
    smiley1: ':)',
    smiley2: ':(',
    smiley3: ':D',
    smiley4: '(y)',
    smiley5: ' :P',
    smiley6: '(wave)',
    smiley7: '(blush)',
    smiley8: '(chuckle)',
    smiley9: '(shocked)',
    smiley10: ':*',
    smiley11: '(n)',
    smiley12: '(search)',
    smiley13: ' <3',
    smiley14: '(oops)',
    smiley15: '(angry)',
    smiley16: '(angel)',
    smiley17: '(sick)',
    smiley18: ';(',
    smiley19: '(bomb)',
    smiley20: '(clap)',
    smiley21: ' ;)'
};

export const regexes = {
    smiley2: /(:-\(\(|:-\(|:\(\(|:\(|\(sad\))/gi,
    smiley3: /(:-\)\)|:\)\)|\(lol\)|:-D|:D)/gi,
    smiley1: /(:-\)|:\))/gi,
    smiley4: /(\(y\)|\(Y\)|\(ok\))/gi,
    smiley5: /(:-P|:P|:-p|:p)/gi,
    smiley6: /(\(wave\))/gi,
    smiley7: /(\(blush\))/gi,
    smiley8: /(\(chuckle\))/gi,
    smiley9: /(:-0|\(shocked\))/gi,
    smiley10: /(:-\*|:\*|\(kiss\))/gi,
    smiley11: /(\(n\))/gi,
    smiley12: /(\(search\))/g,
    smiley13: /(<3|&lt;3|&amp;lt;3|\(L\)|\(l\)|\(H\)|\(h\))/gi,
    smiley14: /(\(oops\))/gi,
    smiley15: /(\(angry\))/gi,
    smiley16: /(\(angel\))/gi,
    smiley17: /(\(sick\))/gi,
    smiley18: /(;-\(\(|;\(\(|;-\(|;\(|:"\(|:"-\(|:~-\(|:~\(|\(upset\))/gi,
    smiley19: /(\(bomb\))/gi,
    smiley20: /(\(clap\))/gi,
    smiley21: /(;-\)|;\)|;-\)\)|;\)\)|;-D|;D|\(wink\))/gi
};
