blank_issues_enabled: false
contact_links:
  - name: Need help with your Jitsi Meet installation?
    url: https://community.jitsi.org
    about: Please post in our community forum.
  - name: Problems using meet.jit.si?
    url: https://community.jitsi.org
    about: Please post in our community forum.
