export const _UPDATE_PRESET_BREAKOUT_ROOMS = '_UPDATE_PRESET_BREAKOUT_ROOMS';

export const _ENABlE_PRESET_BREAKOUT_ROOMS = '_ENABlE_PRESET_BREAKOUT_ROOMS';

export const _RESET_PRESET_BREAKOUT_ROOMS = '_RESET_PRESET_BREAKOUT_ROOMS';

export const _PRESET_BREAKOUT_ROOMS_ADD_LISTENER = '_PRESET_BREAKOUT_ROOMS_ADD_LISTENER';

export const _PRESET_BREAKOUT_ROOMS_CLEAN_LISTENER = '_PRESET_BREAKOUT_ROOMS_CLEAN_LISTENER';

export const _AVAILABLE_TO_SET_BREAKOUT_ROOMS = '_AVAILABLE_TO_SET_BREAKOUT_ROOMS';
