export const OPEN_POPOUT = 'OPEN_POPOUT';
export const CLOSE_POPOUT = 'CLOSE_POPOUT';
export const UPDATE_POPOUT_VIDEO_STREAM = 'UPDATE_POPOUT_VIDEO_STREAM';
export const SET_POPOUT_DISPLAY_MODE = 'SET_POPOUT_DISPLAY_MODE';
export const SET_POPOUT_AVATAR = 'SET_POPOUT_AVATAR';
