
export const SESSION_CREATED = 'SESSION_CREATED';

export const SESSION_STARTED = 'SESSION_STARTED';

export const SESSION_TERMINATED = 'SESSION_TERMINATED';

export const SESSION_FAILED = 'SESSION_FAILED';
