export const ADD_JANE_WAITING_AREA_VIDEO_TRACK = 'ADD_JANE_WAITING_AREA_VIDEO_TRACK';

export const ADD_JANE_WAITING_AREA_AUDIO_TRACK = 'ADD_JANE_WAITING_AREA_AUDIO_TRACK';

export const ADD_JANE_WAITING_AREA_CONTENT_SHARING_TRACK
    = 'ADD_JANE_WAITING_AREA_CONTENT_SHARING_TRACK';

export const JANE_WAITING_AREA_START_CONFERENCE = 'JANE_WAITING_AREA_START_CONFERENCE';

export const SET_DEVICE_STATUS = 'SET_DEVICE_STATUS';

export const SET_JANE_WAITING_AREA_AUDIO_DISABLED = 'SET_JANE_WAITING_AREA_AUDIO_DISABLED';

export const SET_JANE_WAITING_AREA_AUDIO_MUTED = 'SET_JANE_WAITING_AREA_AUDIO_MUTED';

export const SET_JANE_WAITING_AREA_DEVICE_ERRORS = 'SET_JANE_WAITING_AREA_DEVICE_ERRORS';

export const SET_JANE_WAITING_AREA_PAGE_VISIBILITY = 'SET_JANE_WAITING_AREA_PAGE_VISIBILITY';

export const SET_JANE_WAITING_AREA_VIDEO_DISABLED = 'SET_JANE_WAITING_AREA_VIDEO_DISABLED';

export const SET_JANE_WAITING_AREA_VIDEO_MUTED = 'SET_JANE_WAITING_AREA_VIDEO_MUTED';

export const CONNECT_JANE_SOCKET_SERVER = 'CONNECT_JANE_SOCKET_SERVER';

export const UPDATE_REMOTE_PARTICIPANT_STATUSES = 'UPDATE_REMOTE_PARTICIPANT_STATUSES';
