// @flow

/**
 * Redux action type dispatched in order to toggle facial recognition.
 *
 * {
 *      type: SET_FACIAL_RECOGNITION_MODELS_LOADED
 * }
 */

export const SET_FACIAL_RECOGNITION_MODELS_LOADED = 'SET_FACIAL_RECOGNITION_MODELS_LOADED';

export const ADD_FACIAL_EXPRESSION = 'ADD_FACIAL_EXPRESSION';

export const SET_FACIAL_RECOGNITION_ALLOWED = 'SET_FACIAL_RECOGNITION_ALLOWED';

export const SET_DETECTION_TIME_INTERVAL = 'SET_DETECTION_TIME_INTERVAL';

export const UPDATE_CAMERA_TIME_TRACKER = 'UPDATE_CAMERA_TIME_TRACKER';
