/**
 * Event generated by VADReportingService when if finishes creating a VAD report for the monitored devices.
 * The generated objects are of type Array<Object>, one score for each monitored device.
 * @event VAD_REPORT_PUBLISHED
 * @type Array<Object> with the following structure:
 * @property {Date} timestamp - Timestamp at which the compute took place.
 * @property {number} avgVAD - Average VAD score over monitored period of time.
 * @property {string} deviceId - Associate local audio device ID.
 */
export const VAD_REPORT_PUBLISHED = 'vad-report-published';
