// Event generated by a TrackVADEmitter when it emits a VAD score from rnnoise.
// The generated objects are of type VADScore
export const VAD_SCORE_PUBLISHED = 'vad-score-published';

// Event generated by VADReportingService when if finishes creating a VAD report for the monitored devices.
// The generated objects are of type Array<VADReportScore>, one score for each monitored device.
export const VAD_REPORT_PUBLISHED = 'vad-report-published';
