local st = require "util.stanza";
local jid = require "util.jid";

local mod_muc = module:depends("muc");
module:depends("muc_mam");

local get_room_from_jid = mod_muc.get_room_from_jid;

local jid_bare = jid.bare;
local jid_split = jid.split;

local xmlns_retract = "urn:xmpp:message-retract:1";
local xmlns_st_id = "urn:xmpp:sid:0";

-- The MAM archive used by mod_muc_mam.
local archive = module:open_store("muc_log", "archive");

-- Mapping:
--
--   room node
--       message ID -> MAM archive ID
--
-- The original message ID is generated by lib-jitsi-meet.
-- The archive ID is generated by Prosody's archive storage.
local message_archive_map = module:open_store(
    "muc_message_retract",
    "map"
);

if not archive then
    module:log("error", "Unable to open muc_log archive");
    return;
end

if not archive.get then
    module:log(
        "error",
        "muc_log archive does not support :get(); "
        .. "message retraction cannot be enforced"
    );
    return;
end

if not archive.delete then
    module:log(
        "error",
        "muc_log archive does not support :delete(); "
        .. "message retraction cannot be enforced"
    );
    return;
end

-----------------------------------------------------------------------
-- Helpers
-----------------------------------------------------------------------

local function get_archive_id(stanza, room_jid)
    for tag in stanza:childtags("stanza-id", xmlns_st_id) do
        if tag.attr.by == room_jid then
            return tag.attr.id;
        end
    end

    return nil;
end

local function get_retract_tag(stanza)
    return stanza:get_child("retract", xmlns_retract);
end

local function send_error(origin, stanza, error_type, condition, text)
    origin.send(
        st.error_reply(
            stanza,
            error_type,
            condition,
            text
        )
    );
end

-----------------------------------------------------------------------
-- Track MAM archive IDs
--
-- mod_muc_mam handles muc-add-history at the default priority.
-- Its handler calls archive:append() and then adds:
--
--   <stanza-id xmlns="urn:xmpp:sid:0"
--              by="ROOM_JID"
--              id="MAM_ARCHIVE_ID"/>
--
-- Running at priority -1 means our handler runs afterwards.
-----------------------------------------------------------------------

module:hook("muc-add-history", function(event)
    local room = event.room;
    local stanza = event.stanza;

    if not room or not stanza then
        return;
    end

    -- Only messages need to be tracked.
    if stanza.name ~= "message" then
        return;
    end

    -- A message needs a client supplied ID so that a later retract
    -- can refer to it.
    local message_id = stanza.attr.id;

    if not message_id or message_id == "" then
        return;
    end

    local archive_id = get_archive_id(stanza, room.jid);

    -- If there is no stanza-id then mod_muc_mam did not archive this
    -- message (for example archiving may be disabled for this room).
    if not archive_id then
        return;
    end

    local room_node = jid_split(room.jid);

    message_archive_map:set(
        room_node,
        message_id,
        archive_id
    );

    module:log(
        "debug",
        "Mapped MUC message %s in %s to MAM archive item %s",
        message_id,
        room.jid,
        archive_id
    );
end, -1);

-----------------------------------------------------------------------
-- Handle message retractions
--
-- MUC messages are sent to the room's bare JID and therefore arrive
-- through message/bare.
--
-- Priority 1 is deliberately before Prosody's MUC message handler,
-- which uses a lower priority.
-----------------------------------------------------------------------

module:hook("message/bare", function(event)
    local origin = event.origin;
    local stanza = event.stanza;

    if not stanza or stanza.name ~= "message" then
        return;
    end

    if stanza.attr.type ~= "groupchat" then
        return;
    end

    local retract = get_retract_tag(stanza);

    if not retract then
        return;
    end

    local room_jid = jid_bare(stanza.attr.to or "");

    if not room_jid then
        return;
    end

    local room = get_room_from_jid(room_jid);

    if not room then
        send_error(
            origin,
            stanza,
            "cancel",
            "item-not-found",
            "Room not found"
        );

        return true;
    end

    local message_id = retract.attr.id;

    if not message_id or message_id == "" then
        send_error(
            origin,
            stanza,
            "modify",
            "bad-request",
            "Missing message ID"
        );

        return true;
    end

    local actor = stanza.attr.from;

    if not actor then
        send_error(
            origin,
            stanza,
            "auth",
            "forbidden",
            "Unable to identify sender"
        );

        return true;
    end

    -------------------------------------------------------------------
    -- Resolve the sender to their MUC occupant JID.
    --
    -- The original archived MUC message uses the occupant JID in its
    -- "from" attribute, while the incoming stanza contains the real
    -- sender JID.
    -------------------------------------------------------------------

    local actor_nick = room:get_occupant_jid(actor);

    if not actor_nick then
        send_error(
            origin,
            stanza,
            "auth",
            "forbidden",
            "Sender is not an occupant of this room"
        );

        return true;
    end

    local room_node = jid_split(room_jid);

    -------------------------------------------------------------------
    -- Find the MAM archive ID corresponding to the client message ID.
    -------------------------------------------------------------------

    local archive_id = message_archive_map:get(
        room_node,
        message_id
    );

    if not archive_id then
        module:log(
            "warn",
            "Retraction requested for unknown message %s in room %s by %s",
            message_id,
            room_jid,
            actor
        );

        send_error(
            origin,
            stanza,
            "modify",
            "item-not-found",
            "Original message not found"
        );

        return true;
    end

    -------------------------------------------------------------------
    -- Retrieve the original archived message.
    -------------------------------------------------------------------

    local original, err = archive:get(
        room_node,
        archive_id
    );

    if not original then
        module:log(
            "warn",
            "Could not retrieve archive item %s for message %s: %s",
            archive_id,
            message_id,
            tostring(err)
        );

        -- Remove stale mapping.
        message_archive_map:set(
            room_node,
            message_id,
            nil
        );

        send_error(
            origin,
            stanza,
            "modify",
            "item-not-found",
            "Original message not found"
        );

        return true;
    end

    -------------------------------------------------------------------
    -- Server-side ownership validation.
    --
    -- This is the security-critical part.
    --
    -- original.attr.from is the occupant JID that sent the original
    -- message, for example:
    --
    --   room@conference.example.com/Alice
    --
    -- actor_nick is the current occupant JID belonging to the real
    -- sender.
    -------------------------------------------------------------------

    if original.attr.from ~= actor_nick then
        module:log(
            "warn",
            "Unauthorized retraction: %s attempted to retract "
            .. "message %s owned by %s in room %s",
            actor,
            message_id,
            tostring(original.attr.from),
            room_jid
        );

        send_error(
            origin,
            stanza,
            "auth",
            "forbidden",
            "You can only retract your own messages"
        );

        return true;
    end

    -------------------------------------------------------------------
    -- Remove the original message from MAM.
    --
    -- Prosody's archive API deletes by the generated archive key,
    -- not by the client message ID.
    -------------------------------------------------------------------

    local deleted, delete_err = archive:delete(
        room_node,
        {
            key = archive_id;
        }
    );

    if not deleted or deleted < 1 then
        module:log(
            "error",
            "Failed to remove archive item %s for message %s "
            .. "in room %s: %s",
            archive_id,
            message_id,
            room_jid,
            tostring(delete_err)
        );

        send_error(
            origin,
            stanza,
            "wait",
            "internal-server-error",
            "Unable to retract archived message"
        );

        return true;
    end

    -------------------------------------------------------------------
    -- Remove the mapping after successful archive deletion.
    -------------------------------------------------------------------

    message_archive_map:set(
        room_node,
        message_id,
        nil
    );

    -------------------------------------------------------------------
    -- Broadcast the valid retraction.
    --
    -- We do this ourselves because this handler returned true before
    -- normal MUC processing. That also prevents the retraction itself
    -- from being stored in MAM by mod_muc_mam.
    --
    -- MUC messages must be broadcast using the occupant JID rather
    -- than the real sender JID.
    -------------------------------------------------------------------

    local announcement = st.clone(stanza);

    announcement.attr.from = actor_nick;
    announcement.attr.to = room_jid;

    room:broadcast_message(announcement);

    module:log(
        "info",
        "Message %s retracted by %s in room %s; "
        .. "MAM archive item %s deleted",
        message_id,
        actor,
        room_jid,
        archive_id
    );

    -- Stop normal MUC processing. We already performed the operation.
    return true;
end, 1);
