export const SET_CALENDAR_DURATION = 'SET_CALENDAR_DURATION';
export const SET_TIME_TIMER_ACKNOWLEDGED = 'SET_TIME_TIMER_ACKNOWLEDGED';
export const SET_TIME_TIMER_EXPIRED = 'SET_TIME_TIMER_EXPIRED';
export const SET_TIME_TIMER_WARNING_TRIGGERED = 'SET_TIME_TIMER_WARNING_TRIGGERED';
export const START_TIME_TIMER = 'START_TIME_TIMER';
export const STOP_TIME_TIMER = 'STOP_TIME_TIMER';
export const TICK_TIME_TIMER = 'TICK_TIME_TIMER';
