/**
 * Action type to INIT_DEVICE.
 */
export const SET_DESKTOP_SOURCES = 'INIT_DESKTOP_SOURCES';

/**
 * Action type to DELETE_DESKTOP_SOURCES.
 */
export const DELETE_DESKTOP_SOURCES = 'DELETE_DESKTOP_SOURCES';
