export const ENABLE_JANE_WAITING_AREA_PAGE = 'ENABLE_JANE_WAITING_AREA_PAGE';
export const UPDATE_REMOTE_PARTICIPANT_STATUSES = 'UPDATE_REMOTE_PARTICIPANT_STATUSES';
export const SET_JANE_WAITING_AREA_AUTH_STATE = 'SET_JANE_WAITING_AREA_AUTH_STATE';
